# Generated by Django 4.0.7 on 2022-09-17 18:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sendEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('datos', models.CharField(blank=True, max_length=500)),
                ('completo', models.BooleanField(default=False)),
                ('fecha_espera', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email',
            },
        ),
    ]
