# Generated by Django 4.0.7 on 2022-09-17 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('horus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='fecha_espera',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
